### ISSUE TITLE
FIXED: Not working with Brackets on Windows 10

### ISSUE THREAD

**Issue by ancientsandcat** [instilledbee/run-love2d#2]
Fixed by adding LOVE to System Environment PATH variable. Probably worth mentioning in readme file.

**Comment by instilledbee** [comment]
Hi @ancientsandcat, thanks for bringing this up. Would you like to submit a pull request for the README as part of the Installation instructions? 😄

**Comment by ancientsandcat** [comment]
Done :) thank you.
